### ISSUE TITLE
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by bkowshik** [mapbox/robosat#103]
Ref: https://github.com/mapbox/robosat/pull/64

Looks like we the script currently handles only Polygon features and not MultiPolygon features.

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/robosat/robosat/tools/__main__.py", line 57, in <module>
    args.func(args)
  File "/app/robosat/robosat/tools/merge.py", line 69, in main
    merged = shapely.geometry.polygon.orient(merged, sign=1.0)
  File "/usr/local/lib/python3.5/dist-packages/shapely/geometry/polygon.py", line 392, in orient
    ring = polygon.exterior
AttributeError: 'MultiPolygon' object has no attribute 'exterior'
```

**Comment by daniel-j-h** [comment]
@bkowshik is this a problem with upstream shapely? Or do we need to iterate over a multi-polygon's polygons and manually orient them toggling the orientation for every polygon? Could you run this out since it's blocking the end-to-end robosat pipeline.

**Comment by DaielChom** [comment]
Good morning,I use post-productions functions with my own dataset and i have the same problem.

**Comment by daniel-j-h** [comment]
Looks like we are using the `orient` function wrongly. The docs state it works on polygons:

http://toblerity.org/shapely/manual.html#shapely.geometry.polygon.orient

A MultiPolygon has an `geoms` attribute which is a sequence of polygons:

http://toblerity.org/shapely/shapely.geometry.html#module-shapely.geometry.multipolygon

If we want to follow the right-hand rule for multi-polygons we need to be explicit here:

https://github.com/mapbox/robosat/blob/d8eebc9f361d64a84e1774d95877d1906abf1784/robosat/tools/merge.py#L69

**Comment by daniel-j-h** [comment]
Fixed with https://github.com/mapbox/robosat/pull/113.
