### ISSUE TITLE
Tool to create training/validation sets

### ISSUE THREAD

**Issue by Jesse-jApps** [mapbox/robosat#110]
I might have overlooked this feature but I think a it would be nice to have a tool to create training and validation data folder as expected by the train tool.
Additional argument would be the relative size of the validation set.

**Comment by daniel-j-h** [comment]
There's a similar discussion going on in https://github.com/mapbox/robosat/issues/93

**Comment by daniel-j-h** [comment]
Let's keep discussion in #93.
