### ISSUE TITLE
./rs cover fails on "road"

### ISSUE THREAD

**Issue by neverwiredhouse** [mapbox/robosat#114]
**STEP1:**
`./rs extract --type road ../osmPbf/utah-latest.osm.pbf ../osmPbf/road-extraction.geojson`

**STEP2:**
`./rs cover --zoom 18 ../osmPbf/road-extraction.geojson ../osmPbf/utah-road-feature-cover.csv`

**Fail Log:**

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/connor/Documents/Regia/ProjectApollo/building-ccn/robosat/robosat/tools/__main__.py", line 57, in <module>
    args.func(args)
  File "/home/connor/Documents/Regia/ProjectApollo/building-ccn/robosat/robosat/tools/cover.py", line 30, in main
    tiles.extend(map(tuple, burntiles.burn([feature], args.zoom).tolist()))
  File "/home/connor/.local/lib/python3.6/site-packages/supermercado/burntiles.py", line 54, in burn
    bounds = find_extrema(polys)
  File "/home/connor/.local/lib/python3.6/site-packages/supermercado/burntiles.py", line 22, in find_extrema
    xMax = totalArr[:, 0].max() - epsilon
IndexError: too many indices for array

```

**Comment by daniel-j-h** [comment]
Hey hey, support for roads got added recently in https://github.com/mapbox/robosat/pull/111. @DragonEmperorG could you have a look what's going on here?

@neverwiredhouse could you check that all geometry types in the extracted GeoJSON are polygons? Or if there are e.g. linestrings in there?

**Comment by neverwiredhouse** [comment]
Thanks for the quick reply, I'll check that all of them are of type "LineString" in a second.

Link to the file created [HERE](https://www.dropbox.com/s/a18gckwy5ka12wg/road-extraction.geojson?dl=0)

To replicate though, I used the latest utah osm pbf from [Geofabrik](https://download.geofabrik.de/north-america/us/utah.html)

**Comment by neverwiredhouse** [comment]
You the man @DragonEmperorG !!!!

I felt like the bug was more complicated considering the error, but once you revealed it's simplicity I made this change and everything worked properly:

![screenshot from 2018-09-16 15 59 55](https://user-images.githubusercontent.com/22302485/45601448-2334df00-b9ca-11e8-8e86-0dc3f63c6830.png)


Line 151 I just added `if feature.geometry.coordinates:` .. I think that's the most pythonic way of checking if the array is empty, not my primary language, LOL.

Thanks for your time @DragonEmperorG and @daniel-j-h

**Comment by daniel-j-h** [comment]
@DragonEmperorG why are there null features / empty coordinates? This should never come out of `rs extract` in the first place, no?

**Comment by DragonEmperorG** [comment]
Sorry, I'm busy these days. I've checked original "utah-latest.osm.pbf" file. In the extract progress, there is a way which has the tags below. "highway=service,lanee=0" makes the "road_width=0.0". So, in the buffer process, it gets "POLYGON EMPTY" which leads to a null feature. There must be some codes to deal with this special case.
![tim 20180921212213](https://user-images.githubusercontent.com/24807062/45883787-ad26e280-bde4-11e8-82a4-51d882bfa5f7.png)
![tim 20180921213229](https://user-images.githubusercontent.com/24807062/45884272-15c28f00-bde6-11e8-921b-2935e021608f.png)

**Comment by daniel-j-h** [comment]
Fixed with https://github.com/mapbox/robosat/pull/119 - I tested this with the files you provided. Could reproduce the issue and confirm the fix working. Hope that helps. Happy :robot: -ing! :tada:
