### ISSUE TITLE
Support for multispectral images? 

### ISSUE THREAD

**Issue by acannistra** [mapbox/robosat#117]
Would be great to bring in multispectral imagery into this really fantastic pipeline. It seems like both the `png` and `webp` formats don't have support for more than 3+alpha bands, which might kill this idea preflight, but I'm interested in looking into it. 

The `robosat.unet` code has some [suggestion](https://github.com/mapbox/robosat/blob/a9ad0d348d7cd4ebb6c75a570e28ba6b94347522/robosat/unet.py#L92) that there was an idea to do this. 

https://github.com/mapbox/robosat/blob/a9ad0d348d7cd4ebb6c75a570e28ba6b94347522/robosat/unet.py#L92

Any progress? Might it ever happen?

**Comment by daniel-j-h** [comment]
There's a ticket already tracking this: https://github.com/mapbox/robosat/issues/56 let's centralize discussion there.

It's certainly possible and on our radar; if you want to help out here that would be great. The basic idea is to use n input channels in the model using the pre-trained weights and zero-initializing new channels. The datasets might need to change a bit but we can use our cocatenation dataset to let users provide multiple slippy map dirs (e.g. one for rgb, one for additional depth, etc.).

**Comment by acannistra** [comment]
Ah, didn't see that. I'll see if there's bandwidth for that. Thanks for the heads-up!

**Comment by daniel-j-h** [comment]
Great! Feel free to hit me up if you need guidance or are running into problems!
