### ISSUE TITLE
What is a meaning of extracting clouds ?

### ISSUE THREAD

**Issue by toren77** [mapbox/robosat#121]
Taken from here : Extracts features such as: buildings, parking lots, roads, water, clouds
Thanks !

**Comment by daniel-j-h** [comment]
You can use robosat to create a cloud mask for satellite imagery.

Look around for example for the Sentinel 2 pre-computed cloud mask which is quite coarse and has its problems. There are also some prior experiments out in the wild, see for example:

- http://cs231n.stanford.edu/reports/2017/posters/561.pdf
- http://cs231n.stanford.edu/reports/2017/pdfs/561.pdf

You can see clouds as an example which shows robosat's ability to generalize across datasets, features, and use-cases. We are not bound to for example buildings and OpenStreetMap for a training set.

Here is an example image from Sentinel 2, last week, over Berlin, Germany:

https://apps.sentinel-hub.com/eo-browser/?lat=52.4857&lng=13.3937&zoom=11&time=2018-09-24&preset=1_TRUE_COLOR&datasource=Sentinel-2%20L1C

![clouds](https://user-images.githubusercontent.com/527241/46315647-49fc3380-c5ce-11e8-91b0-a84d9d00f22d.png)

Once you have a fine-detailed cloud mask you can for example do analysis with it, build a cloudless satellite layer, and so on.

Hope that helps.

**Comment by azupanc** [comment]
There exist better alternatives to the Sentinel 2 pre-computed cloud masks that are provided by ESA. In certain regions (only Europe at the moment) better quality Sentinel-2 products are available (L2A), which come with so called scene classification map. These maps include cloud masks as well. The scene classification map for the above image of Berlin looks like:

![screen shot 2018-10-02 at 08 36 26](https://user-images.githubusercontent.com/24294299/46332878-6de76580-c61e-11e8-90c4-356533943598.png)

 https://apps.sentinel-hub.com/eo-browser/?lat=52.4857&lng=13.3937&zoom=11&time=2018-09-24&preset=1_TRUE_COLOR&datasource=Sentinel-2%20L1C

There are other alternatives as well, which may be used elsewhere. See for example https://medium.com/sentinel-hub/improving-cloud-detection-with-machine-learning-c09dc5d7cf13

**Comment by daniel-j-h** [comment]
The blog post you linked to is great! Thanks for sharing and writing :)

Closing here as not actionable on our side.

**Comment by AhmadAmmar** [comment]
How can I download/bring-in Sentinel-2 imagery in Slippy Tile format to get it working with Robosat?
