### ISSUE TITLE
Created Multiple Geojson Files

### ISSUE THREAD

**Issue by fevzidas** [mapbox/robosat#150]
Hello,

When I run the "**rs extract --type building map.osm.pbf buildings.geojson"** command multiple .geojson files are created such as 
buildings-8ec3d5a01c7c495abc91cb135f6b083b.geojson
buildings-781d63a403bf4750a725fa4763ced204.geojson
...

Do you have any idea about this issue?

Best regards.

**Comment by daniel-j-h** [comment]
Sure, it's batching feature extraction so the memory consumption stays low and we flush files every n objects to disk. See https://github.com/mapbox/robosat/pull/148. There is now also a batch argument you can tune for smaller or larger batch sizes. Hope that helps.

**Comment by fevzidas** [comment]
Thank you very much for your answer :)
