### ISSUE TITLE
Re-enable automated docker builds

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/robosat#153]
Looking at https://hub.docker.com/r/mapbox/robosat/tags automated docker builds stopped working.

In the logs (https://travis-ci.org/mapbox/robosat/builds/536326116#L722) we see

> Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

@jacquestardie could you look into this; the login probably changed and needs to be fixed in the Travis env so that the Travis workers can automatically build and push images.

See our Travis file here

https://github.com/mapbox/robosat/blob/bde13538ab85849d21e2c10e2e67ecb082296c3b/.travis.yml#L38-L58

**Comment by daniel-j-h** [comment]
From the docker security issue last month

> For users with autobuilds that may have been impacted, we have revoked GitHub tokens and access keys, and ask that you reconnect to your repositories and check security logs to see if any unexpected actions have taken place.

Sounds like we just may have to re-enable autobuilds.

**Comment by jacquestardie** [comment]
Will take a look at this tomorrow @daniel-j-h.

**Comment by daniel-j-h** [comment]
@jacquestardie when can I expect an update here? Folks should use our pre-buillt docker images which we can provide guarantees for. Otherwise they may run e.g. into segmentation faults like [this person just reported](https://www.openstreetmap.org/user/daniel-j-h/diary/44321#comment44869).

**Comment by jacquestardie** [comment]
:gift: https://cloud.docker.com/u/mapbox/repository/docker/mapbox/robosat/general

Credentials updated, I think we're all set here. Going to let you test and close this out @daniel-j-h.

**Comment by daniel-j-h** [comment]
Thanks :santa: !

Your link 404s for me - I probably don't have the permissions for the docker cloud.

https://hub.docker.com/r/mapbox/robosat/tags looks good, there are two latest tags from an hour ago (and a `test` tag that you probably created - can you delete it please). Did you manually trigger those builds?

Travis only builds and pushes docker images for master and for tags, see

https://github.com/mapbox/robosat/blob/27833dae809d1b08463a21e71e2ad2fd3320b73a/.travis.yml#L37-L57

to test the end to end pipeline here we should probably just commit to master (push empty commit to trigger Travis).

**Comment by daniel-j-h** [comment]
Just did this in https://github.com/mapbox/robosat/commit/a855a8a0095a8eca284a074680b5eb82faa31abc if you log into docker hub (or cloud?) you should be able to verify the pipeline working again. If that's the case please close here.

**Comment by jacquestardie** [comment]
Pushed the `test` image locally - and just removed it from DockerHub. The other two you mentioned were built from a Travis build which I retriggered.

:sparkles:

**Comment by daniel-j-h** [comment]
Coolio! Thank you! :bow:
