### ISSUE TITLE
Prepare v1.2.0 release

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/robosat#164]
The last v1.1.0 release was last year in September - we should do another release.

From https://github.com/mapbox/robosat/compare/v1.1.0...master a release would include
- road handler
- lovasz loss
- new metrics
- fine tune and continue training
- osm data edge case fixes
- better building dataset creation from osm data
- cuda 10, pytorch 1.1

In addition good potential tickets to also include are
- https://github.com/mapbox/robosat/issues/16 simplification issue
- https://github.com/mapbox/robosat/pull/88 generic zoom level handling
- https://github.com/mapbox/robosat/pull/75 decide on fpn
- https://github.com/mapbox/robosat/pull/161 decide on scse

And we are blocked by
- [x] https://github.com/mapbox/robosat/pull/154 - up to date docs
- [x] https://github.com/mapbox/robosat/issues/153 - automated docker image builds
- [x] https://github.com/mapbox/robosat/pull/163 - fix travis integration

@jacquestardie I can not push tags or create a release here on Github. How do we move forward?

**Comment by jacquestardie** [comment]
Hoping to have an answer to that in a few days - will update here once there's a clear path forward.

**Comment by daniel-j-h** [comment]
We managed to unblock all our hard requirements for this release pretty quickly. I will do a v1.2.0 release now - the fpn / scse / fpa changes are currently queued up on my rig but it takes a while to crunsh through them. Let's get this out first and then iterate on it.

**Comment by daniel-j-h** [comment]
Release is out! https://github.com/mapbox/robosat/releases/tag/v1.2.0

And wrote about it here: https://www.openstreetmap.org/user/daniel-j-h/diary/44321

Feel free to make noise about this! :)

**Comment by maning** [comment]
correct link to diary: https://www.openstreetmap.org/user/daniel-j-h/diary/368726

time to give it a spin again ;)
