### ISSUE TITLE
rs download does sth. wrong when creating the url for the api

### ISSUE THREAD

**Issue by JannisEgelhof** [mapbox/robosat#173]
Execution of rs download:
![warning](https://user-images.githubusercontent.com/29760462/60169810-b6c3f780-9807-11e9-875c-f650b8d08ea8.PNG)

Result when called in browser:
![api_result](https://user-images.githubusercontent.com/29760462/60169841-c0e5f600-9807-11e9-9475-66e1db91f729.PNG)

**Comment by daniel-j-h** [comment]
Could you provide a bit more information? How do you call `rs download`?

In the end all `rs download` is doing is a simple http call to the url you provide.

**Comment by JannisEgelhof** [comment]
I tried it again. Seems to me that I made sth. wrong. Sorry.

**Comment by JannisEgelhof** [comment]
I am sorry. Analyzed my call again. Seems to me that I did sth. wrong. Now it works with Mapbox.

**Comment by himanshu-sikaria** [comment]
@JannisEgelhof can you share what you were doing wrong here? I am facing the same issue
