### ISSUE TITLE
Can't run RoboSat docker image

### ISSUE THREAD

**Issue by karkal6123** [mapbox/robosat#174]
Hello all,

since the 1.2.0 release I am having issues with "Docker run" command - cannot run the container for RoboSat docker image at all. I can see the list with all robosat tools/ commands, however, accessing the application root doesn't work... Please have a look:

![Docker_image_issue](https://user-images.githubusercontent.com/52357984/60388199-468acf80-9aae-11e9-9190-307e5d67cebf.png)

Could you give me a hint, please?

I am running the Docker Desktop on Windows 10 Pro that uses Hyper-V's MobyLinuxVM.

With best wishes guys and looking forward to getting some help.

Karoline

**Comment by jacquestardie** [comment]
@karkal6123, are you able to pass in specific commands? 

```sh
# ie: does something like this work for you?
# note the `cover --help` commands at the end
docker run -it --rm -v $PWD:/data --ipc=host --network=host mapbox/robosat:latest-cpu cover --help
```

Your `ls` command makes me think you're attempting to `ls` from within the container, in which case you'll need to do something like:
```sh
$ docker run -it --rm -v $PWD:/data --ipc=host --network=host --entrypoint /bin/bash mapbox/robosat:latest-cpu
root@compuder:/usr/src/app# ls
config  docker  requirements.txt  robosat  rs
```

Hope that's helpful :tipping_hand_man:

**Comment by karkal6123** [comment]
Thank you @jacquestardie  !!!

Brilliant, it does work now. 

![Docker_image_issue_3](https://user-images.githubusercontent.com/52357984/60388574-0a5a6d80-9ab4-11e9-97a2-feb55d921980.png)

**Comment by dakmatt** [comment]
thanks, this work for me too
