### ISSUE TITLE
Generalize tile resolution in tools

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/robosat#18]
We work with 512x512 pixel image tiles at the moment.
- There is no guarantee this is the user's image resolution, though.
- At the same time no tool is bound to this resolution and should work e.g. with 256x256 image tiles, too.

Tasks:
- [ ] Generalize all tools and functions to accept a tile resolution argument the user can pass in

**Comment by tomass** [comment]
Using images with 256x256 size.
`image_size = 256` in model file.
`rs download ext=jpeg` downloads correct 256 size images.
`rs rasterize --size=256` creates correct 256 size png's.
but
`rs predict` creates 512x512 size prediction images like these (ignore the quality as this was a test run with only a hundred of samples to train from)
![81619](https://user-images.githubusercontent.com/969513/41506224-90c27f2c-7222-11e8-88bb-b5af514f80f4.png)

**Comment by daniel-j-h** [comment]
Are you using https://github.com/mapbox/robosat/pull/30 ? I just the open pull request and fixed the predict tool not properly passing on the `--tile_size` command line argument. Could you give it another try with `--tile_size 256`?

**Comment by tomass** [comment]
After adding #30, problem with tile size is gone. Thank you!
