### ISSUE TITLE
rs cover creates incorrect .tiles file

### ISSUE THREAD

**Issue by JannisEgelhof** [mapbox/robosat#181]
Hello :),
I have a weird problem with rs cover.
I use the following tms-link which is from openaerialimagery: 
http://tiles.openaerialmap.org/1/0/55c3c39a2b67227a79b4f4e2/{z}/{x}/{y}.png
This is the id: 59e62b703d6412ef72208f33
Thats the link to the tif file: 
http://oin-hotosm.s3.amazonaws.com/1/0/55c3c39a2b67227a79b4f4e2.tif
I cut out the bbox with `osmium`.  This is the result, when I check the osm.pbf file in qgis.

![grafik](https://user-images.githubusercontent.com/29760462/63864188-b5ea4600-c9af-11e9-82fd-628d47f42ecd.png)

With `rs extract` i got a geojson file. I tested it in qgis. It was shown at the correct position

![grafik](https://user-images.githubusercontent.com/29760462/63864123-9d7a2b80-c9af-11e9-8220-e94e5bc9152f.png)

With rs cover I created a tiles file. It seems to me that they were wrong.

> 222098,122829,18
> 222090,122827,18
> 222090,122828,18
> 222091,122832,18
> 222096,122831,18
> 222095,122834,18
> 222100,122827,18
> 222096,122828,18
> 222095,122833,18
> ...

_They are located somewhere in the sea.
Therefore the aerial images could not be downloaded correctly.
Is there a mistake on my side?

Maybe an error with supermercado?_

Ok I read a bit more and saw the transformation described on this page: [https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames]

Today it works again. So maybe it has to do something with rs download.

**Comment by daniel-j-h** [comment]
> Today it works again. So maybe it has to do something with rs download.

So is it working for you again now?

The only known tile issue so far is https://github.com/mapbox/robosat/issues/10 which seems like due to some edge case handling if I remember correctly.
