### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by dakmatt** [mapbox/robosat#185]
Hi,

I got the following error after installation rs into Centos with python3.6. 

[root@localhost robosat]# ./rs
./rs: line 3: 27181 Segmentation fault      python3 -m robosat.tools "$@"

Any idea?

**Comment by daniel-j-h** [comment]
Use the pre-built docker images or build and run the Dockerfile yourself. If you can not reproduce it in the Docker container then we're all good here.

We use native dependencies (mostly through Python wheels) and they probably don't support ancient CentOS libc versions (my first guess here).

**Comment by daniel-j-h** [comment]
Any updates here @dakmatt ?

**Comment by daniel-j-h** [comment]
Stale. Use our pre-built docker images for a self-contained reproducible environment.
