### ISSUE TITLE
What is the best way to cite robosat?

### ISSUE THREAD

**Issue by SBCV** [mapbox/robosat#186]
Is there a corresponding paper?

**Comment by SBCV** [comment]
I guess it is this paper: [http://conference.scipy.org/proceedings/scipy2018/pdfs/virginia_ng.pdf](http://conference.scipy.org/proceedings/scipy2018/pdfs/virginia_ng.pdf)

**Comment by daniel-j-h** [comment]
This is not the paper for robosat. Please just cite this Github repository and/or the initial release blog post at https://blog.mapbox.com/meet-robosat-af42530f163f
