### ISSUE TITLE
Request : 

### ISSUE THREAD

**Issue by sumitjangir8796** [mapbox/robosat#197]
How to use to Docker in Windows OS ?
Please share a video having fresh installation of Mapbox/Roboset in Windows OS.

**Comment by dorbodwolf** [comment]
you can use docker in windows but only the cpu
version not the gpu version. it's same as in linux.

**Comment by daniel-j-h** [comment]
This is out of scope for robosat.

We expect docker / nvidia-docker to be installed for cpu / gpu, respectively.

It will work on Linux and macOS; Windows folks are on their own.
