### ISSUE TITLE
questions related to offline geotiff image and export option

### ISSUE THREAD

**Issue by jaigsingla** [mapbox/robosat#200]
Hi, 
It looks very nice development. I have few queries:

1.Can we run this module on Geotiff image already available in my machine if yes, how? how to convert it to slippy map format ? do one requires full scene or multiple pieces of one scene?
2. Pls give guidelines for offline (without internet ) processing.

3. If I have segmented version (classified building image in png format) of the images available and just want to use your post processing tool  for saving in to geojson or shape file, how to do that ?

thanks

**Comment by daniel-j-h** [comment]
1. Robosat only works with slippy map tiles; you can tile e.g. into 256x256 or 512x512 pixel tiles via
- https://gdal.org/programs/gdal2tiles.html
- https://github.com/cogeotiff/rio-tiler

Here's a quick and unoptimized tiler script; if your use case gets more involved you should definitely look into better ways of doing this:

https://gist.github.com/daniel-j-h/69a967d63d833f74a123e2540bd146b9

2. I don't understand what you mean by offline processing. All tools except for downloading satellite tiles from a remote server work "offline".

3. Only use the post-processing tools then.

**Comment by ocourtin** [comment]
@jaigsingla, to complete @daniel-j-h answer, on imagery tiling:
You could also give a look on `rsp tile`, from https://github.com/datapink/robosat.pink
Usually faster than the others, able to deal with coverage imagery, and to skip nodata tiles...

HTH,

**Comment by jaigsingla** [comment]
> 1. Robosat only works with slippy map tiles; you can tile e.g. into 256x256 or 512x512 pixel tiles via
> 
> * https://gdal.org/programs/gdal2tiles.html
> * https://github.com/cogeotiff/rio-tiler
> 
> Here's a quick and unoptimized tiler script; if your use case gets more involved you should definitely look into better ways of doing this:
> 
> https://gist.github.com/daniel-j-h/69a967d63d833f74a123e2540bd146b9
> 
> 1. I don't understand what you mean by offline processing. All tools except for downloading satellite tiles from a remote server work "offline".
> 2. Only use the post-processing tools then.

Hello daniel,
All tools are offline , I agree. But how to install and use this library on offline machine is a difficult task.

Request  you provide all dependencies as a zip or virtual environment image >>

thanks

**Comment by daniel-j-h** [comment]
Look into

    docker image save
    docker image load

to create a self-contained docker image tarball, get it onto your machine, and load it again.

**Comment by jaigsingla** [comment]
Hi daniel,
I could build everything offline. Now i want to use it along with bavaria dataset :
Following is available in datasets:
Model  as check point 
geojson file of the heat map area
two comparison images 

After going through your post, we need followings:
1.Any geo-referenced image 
2. From building shape file, OSM extract in geoson format of that area. 
3. these two files should be converted to slippy format using ./rs cover 
4. rs rasterize on osm slippy format files 
5. rs train like that 

I want to simulate entire scenario using bavaria data-sets first but i am unable to fetch the same. 
pls guide.

**Comment by daniel-j-h** [comment]
Please read the documentation for our tools and read through the diary posts here

https://github.com/mapbox/robosat#overview

they explain in detail how to run the pipeline, where to get the training data from, and so on.

**Comment by jaigsingla** [comment]
ok thanks. 
I am directly starting with my own data. i executed ./rs cover --zoom 20 .geojson building.tiles 
but it gives error of xy() takes from 2 to 3 positional arguments but 5 were given.

**Comment by daniel-j-h** [comment]
Do you have a stack trace? Which version are you running, latest? How does your geojson file look like?

**Comment by jaigsingla** [comment]
Stack trace. I used latest version only. geojson file is clipped over Ahmedabad, India .

 0%|                                                                                                           | 0/482 [00:00<?, ?feature/s]
Traceback (most recent call last):
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/deep/building_extraction/robosat-master/robosat/tools/__main__.py", line 58, in <module>
    args.func(args)
  File "/home/deep/building_extraction/robosat-master/robosat/tools/cover.py", line 30, in main
    tiles.extend(map(tuple, burntiles.burn([feature], args.zoom).tolist()))
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/supermercado/burntiles.py", line 62, in burn
    all_touched=True)
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/rasterio/env.py", line 397, in wrapper
    return f(*args, **kwds)
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/rasterio/features.py", line 280, in rasterize
    for index, item in enumerate(shapes):
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/supermercado/burntiles.py", line 59, in <genexpr>
    ((project_geom(geom['geometry']), 255) for geom in polys),
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/supermercado/burntiles.py", line 12, in project_geom
    for part in geom['coordinates']
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/supermercado/burntiles.py", line 12, in <listcomp>
    for part in geom['coordinates']
  File "/home/deep/anaconda3/envs/fastai/lib/python3.6/site-packages/supermercado/burntiles.py", line 11, in <listcomp>
    [mercantile.xy(*coords) for coords in part]
TypeError: xy() takes from 2 to 3 positional arguments but 5 were given

**Comment by daniel-j-h** [comment]
How did you generate the GeoJSON? What type of features do you have in there? From what I can recall we were supporting "Polygon" features only due to the supermercado dependency limitations.

For our extract tool see

https://github.com/mapbox/robosat/blob/3ae9c7e1d58fc446b7c8df3835c628c40ca85ba2/robosat/osm/building.py

And supermercado upstream tickets
- https://github.com/mapbox/supermercado/issues/13
- https://github.com/mapbox/supermercado/issues/30

**Comment by jaigsingla** [comment]
There is osm building shape file available over ahmedabad. Cropped subset over Ahmedabad was taken as an input and using QGIS I just saved this in geojson format and use for further processing.

**Comment by daniel-j-h** [comment]
Yeap you have features in there which are not Polygon. The upstream supermercado library does not support that, see tickets linked above. I recommend you generate a GeoJSON file with Polygon features only.

**Comment by ocourtin** [comment]
@jaigsingla  You could also give a try to `rsp rasterize` resilient with all GeoJSON geometries types.

Cf: 
 - https://github.com/mapbox/robosat/pull/138
 - https://github.com/datapink/robosat.pink/blob/v0.5.5/docs/tools.md#rsp-rasterize

**Comment by jaigsingla** [comment]
@ocourtin can you share practical example of this ? and i guess we need to perform tilling on this also??

**Comment by jaigsingla** [comment]
> Yeap you have features in there which are not Polygon. The upstream supermercado library does not support that, see tickets linked above. I recommend you generate a GeoJSON file with Polygon features only.

@daniel-j-h but these are polygons only ??

**Comment by ocourtin** [comment]
> @ocourtin can you share practical example of this ? 

https://github.com/datapink/robosat.pink/blob/v0.5.5/docs/101.md#retrieve-and-tile-labels

> and i guess we need to perform tilling on this also??

If your labels are vector ones (GeoJSON or PostGIS), `rsp rasterize` performs the tiling for you.
If your labels are PNG ones (it could happens), `rsp tile --label` is the way to deal with...

HTH,

**Comment by jaigsingla** [comment]
@ocourtin what are config and cover parameters here. what inputs shall I give here.

**Comment by jaigsingla** [comment]
> Hi daniel,
> I could build everything offline without docker. Now i want to use it along with bavaria dataset :
> Following is available in datasets:
> Model as check point
> geojson file of the heat map area
> two comparison images
> 
> After going through your post, we need followings:
> 1.Any geo-referenced image
> 2. From building shape file, OSM extract in geoson format of that area.
> 3. these two files should be converted to slippy format using ./rs cover
> 4. rs rasterize on osm slippy format files
> 5. rs train like that
> 
> I want to simulate entire scenario using bavaria data-sets first but i am unable to fetch the same.
> pls guide.

Hi daniel,
I spoiled earlier virtual env and now facing problem of could not find libspatialindex_c library file. I tried to install it offline using conda install  --offline option . but , still error persists.

**Comment by daniel-j-h** [comment]
You'll need libspatialindex - but you really should just use the pre-built docker images so that we can guarantee you have all packages. If you want to install on your own, check out the Dockerfile.

**Comment by jaigsingla** [comment]
daniel, lots of issues to use pre-built docker. I dont have internet on my working machine and it will take lot of time to bring saved docker image here and then do the setup on working machine. so i m prefering to install it one by one. stuck on libspatialindex as last library. i have downloaded this from MIT site and installed using conda offline but still it is not installed .

**Comment by jaigsingla** [comment]
solved again.

**Comment by daniel-j-h** [comment]
Sure why not.

**Comment by jaigsingla** [comment]
ok. 

what I did is as following:

1) Created ds/training/images and ds/training/labels . similar to these ds/validation/images and ds/training/labels are created .
2) calculated weights using ./rs weights dataset_building.toml 
3) run ./rs train using all parameters. 
4) after 50 epochs validation IOU shows 0.45 ??

**Comment by daniel-j-h** [comment]
Okay - so what? How big is your dataset? How did you create it? Did you manually check it if it looks good? What do you want to get out of it? You have to investigate a bit on your own here..

**Comment by jaigsingla** [comment]
My dataset is not that big. it is small image file and osm data file as shared earlier too. I created data in slippy format using commands suggested by ocourtin. Manually , I check slippy files. it is properly placed in folders and looks ok. I want to generated vector shapes from image files. I need directions to investigate

**Comment by daniel-j-h** [comment]
> My dataset is not that big.

Then what do you expect? We need a large dataset to learn from :)

There is only so much magic we can do here.

**Comment by jaigsingla** [comment]
![history-00050-of-00050](https://user-images.githubusercontent.com/25918360/73172033-1bda2580-4128-11ea-918e-7c6fe4aba8cf.png)
![history-00020-of-00020](https://user-images.githubusercontent.com/25918360/73172034-1bda2580-4128-11ea-9a66-3107d01f8a65.png)

shall i proceed with predictions or what you say?

**Comment by daniel-j-h** [comment]
How big is your dataset? How many samples do you have in train and val?

**Comment by jaigsingla** [comment]
Input image size is 777x674 with 4 bands.
i have converted to slippy format using zoom level 19. 
i have used 90% for training and 10% validation.

**Comment by daniel-j-h** [comment]
If you have a single image with 777x674 pixel as your dataset, I don't think you will have much luck training machine learning models on it. It's way too small to learn anything interesting.

**Comment by jaigsingla** [comment]
So should I try on a bigger data set. Can you share sample from your side so that I am sure to get validated output

**Comment by daniel-j-h** [comment]
Check out the diary posts in https://github.com/mapbox/robosat#overview

The Tanzania example is probably as low as you should go with a few thousand of 512x512 tile images. If you follow the Bavaria diary post you can get a much bigger dataset.

**Comment by hamzahkhan** [comment]
> Hi,
> It looks very nice development. I have few queries:
> 
> 1.Can we run this module on Geotiff image already available in my machine if yes, how? how to convert it to slippy map format ? do one requires full scene or multiple pieces of one scene?
> 2. Pls give guidelines for offline (without internet ) processing.
> 
> 1. If I have segmented version (classified building image in png format) of the images available and just want to use your post processing tool  for saving in to geojson or shape file, how to do that ?
> 
> thanks
@jaigsingla Any luck resolving your issue on converting segmented png to geojson? Stuck on same.

**Comment by jaigsingla** [comment]
@hamzahkhan  not tried yet.

**Comment by jaigsingla** [comment]
@daniel-j-h  pls make this Tanzania dataset available as a sample here. it is very difficult to fetch exact dataset without internet.

**Comment by daniel-j-h** [comment]
I no longer have access to the dataset and I'd have to fetch it from scratch myself, too.
