### ISSUE TITLE
rs command doesnt works

### ISSUE THREAD

**Issue by balla-999** [mapbox/robosat#201]
Hi, thanks for this job.
after runing `docker run -it --rm -v $PWD:/data --ipc=host --network=host mapbox/robosat:latest-cpu --help
` it looks like everything is good, but when try to run `rs` command it says "The order "rs" was not found", any idea why is this happening??
thanks
![rs](https://user-images.githubusercontent.com/59870338/72339442-31e7ef00-3701-11ea-84eb-0444591b539f.png)

**Comment by daniel-j-h** [comment]
1. don't run docker under sudo; [add your user to the docker group](https://docs.docker.com/install/linux/linux-postinstall/)
2. read up on docker; if you run docker images, you can't expect their content to be installed on your system. The first command runs the rs tools _inside_ the container, the second command tries to run a system binary called `rs` which does not exist on your system.

**Comment by balla-999** [comment]
@daniel-j-h thanks for your fast reply.
runnig docker without sudo says "Docker dont have permmision", after adding the user to the docker group like you told me, now it says "Docker cannot connect to the docker deamon".
![Captura de pantalla de 2020-01-15 17-53-47](https://user-images.githubusercontent.com/59870338/72424308-b9e0fe00-37c0-11ea-91fd-2bf8cb3359fe.png)
i ran lots of solution i saw online to try to run or restart the docker but no one works, my docker active status still "failed". any idea about what im doing bad? Thank you
![Captura de pantalla de 2020-01-15 18-03-45](https://user-images.githubusercontent.com/59870338/72425087-0c6eea00-37c2-11ea-9dcf-67e6765a1c80.png)
-i also try to add the user to docker group in macOs, and it looks like works, but running `extract` command says "rs: to many arguments"
![Captura de Pantalla 2020-01-15 a la(s) 5 44 49 p  m](https://user-images.githubusercontent.com/59870338/72425286-76878f00-37c2-11ea-8619-93509dcb4eed.png)

**Comment by daniel-j-h** [comment]
Just repeat the docker run command and instead of `--help` say for example `extract`.

**Comment by balla-999** [comment]
> Just repeat the docker run command and instead of `--help` say for example `extract`.

(oh yes! it works, thanks. Sorry, im a beginner in this)
-I solved my Docker problem by the easy way: just uninstall and install again the docker, now it is working, BUT i have another problem now, runing `extract` have the error showed in the picture. searching, it looks like a problem with python, but everything looks normal in my system, online similar problems was solved running `export PYTHONPATH=.:$PYTHONPATH` but it doesnt works for me, any idea? 
(both MacOs and Ubuntu, show the same error)
![Captura de pantalla de 2020-01-17 11-23-28](https://user-images.githubusercontent.com/59870338/72582477-dfcfe500-391d-11ea-87bf-c29ce2fdf8b3.png)

**Comment by daniel-j-h** [comment]
It's at `/data/map.osm.pbf` - please read the docs on docker and it's mounting option.

**Comment by balla-999** [comment]
hi, im back.
running `download` command it tooks more than 5 hours to complete (yes, i ran it on cpu), but it only create the folders without tiles, and terminal shows all the process failed, also the system monitor shows it was downloading something everytime, any idea about this issue?
![Captura de pantalla de 2020-01-23 15-15-27](https://user-images.githubusercontent.com/59870338/72983640-bbdc3a00-3e1c-11ea-8ee1-5c7f8a78ca7d.png)
![Captura de pantalla de 2020-01-23 15-51-30](https://user-images.githubusercontent.com/59870338/72983653-c3034800-3e1c-11ea-9ae0-89ecff8199c5.png)
I think maybe it was something wrong in the past steps, for example: running `extract` it doesnt creat one .geojson file but 12 .geojson files, so i ran `cover` for each one of this then i joined all the .tiles files in only one named buildings.tiles which i used to run `download`, is this normal?
also would like to know if my .tiles files looks like it most to look, and some warnings also make doubt, thank you so much, for any help.
![Captura de pantalla de 2020-01-23 15-05-24](https://user-images.githubusercontent.com/59870338/72984429-a36d1f00-3e1e-11ea-821e-f6a66dd85786.png)
THIS IS MY BUILDINGS.TILES
![Captura de pantalla de 2020-01-22 16-43-22](https://user-images.githubusercontent.com/59870338/72984513-d6171780-3e1e-11ea-956b-041edb4068ca.png)
MY .GEOJSON FILES
![Captura de pantalla de 2020-01-23 20-34-02](https://user-images.githubusercontent.com/59870338/72984935-c5b36c80-3e1f-11ea-9d7a-6b1ab20b9fea.png)

**Comment by daniel-j-h** [comment]
The URL you pass to `rs download` seems to be a single tif. This will not work; it expects an endpoint to download Slippy Map tiles from.

You can just download the tif manually and then you have to tile it into Slippy Map tiles on a specific zoom level. Read up on it here: https://www.openstreetmap.org/user/daniel-j-h/diary/44321

And check out e.g. gdal2tiles. Note: gdal2tiles generates tiles in TMS format, you'd have to flip the y-coordinate for proper Slippy Map tiles, see https://gist.github.com/tmcw/4954720

**Comment by balla-999** [comment]
im following [https://www.openstreetmap.org/user/daniel-j-h/diary/44321](url) but im confuse about where should i take the url from, which i must pass to `rs download`. what i did was use OpenAerialMap Api in the browser `https://api.openaerialmap.org/meta?bbox=38.9410400390625,-7.0545565715284955,39.70458984374999,-5.711646879515092` and copy the uuid, but it shows lots of uuid. today i did it but instead of copy `.tif` url, i copy `.png` url (like in the tutorial), and for first time it works, but it generated 233 folders with only 10 files .webp, I guess its because the url i pass only have that 10, where can i get a unique url which have whole the imagery??
thanks again
THIS IS THE URL WHICH GAVE ME 10 IMAGES
![Captura de pantalla de 2020-01-24 12-06-03](https://user-images.githubusercontent.com/59870338/73043861-05229d00-3ea2-11ea-8492-8d3d48b1ba84.png)

**Comment by daniel-j-h** [comment]
OpenAerialMap creates one Slippy Map endpoint per .TIF file. You need to query many (for multiple .TIFs) and combine their tiles. Or tile the .TIF files on your own (see comments above).

**Comment by balla-999** [comment]
Hii, thanks for all your help, finally i have the dataset and config files ready.
my problem now is while training: it starts well but after few minutes it just stuck
![Captura de pantalla de 2020-01-30 10-12-11](https://user-images.githubusercontent.com/59870338/73414375-a2218200-4349-11ea-87ac-ccd08d166bc0.png)
When i try to exit (pressing ctrl+c) it doesnt works, so i must reset my computer.
any idea about this?
my hardware is: Cpu intel core i7, Ram 32Gb, Gpu two GTX 970. Runing Ubuntu 18.04Lts.
thnak you

**Comment by daniel-j-h** [comment]
Check nvidia-smi or [nvtop](https://github.com/Syllo/nvtop) to monitor your gpu, check htop to monitor your cpus, memory, and swap space (are you swapping?), check iotop to monitor I/O.

Otherwise it's hard to tell what's going on in your setup.

**Comment by balla-999** [comment]
Hi im back, finally it could train well without other changes, thank you.
I ran Tanzania sample with very good results.
I saw this project can work for buildings, parking lots and roads, what about water? is it already implemented to extract water?

**Comment by daniel-j-h** [comment]
You can extend robosat for arbitrary OpenStreetMap features, see

https://github.com/mapbox/robosat#extending

In addition for water I recommend checking out existing ones like the Sentinel scene classification mask.
