### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by aleksandrmelnyk** [mapbox/robosat#203]
Hi all,
Am getting Illegal instruction (core dumped) when trying to run downoad, like this:
`sudo docker run -it --rm -v $PWD:/data --ipc=host --network=host mapbox/robosat:latest-cpu download https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}@2x.webp?access_token=xxxxxx.N-t2ynPPxbomsFIK41SVLA /data/cover/buildings.csv /data/tiles/buildings`

what could it be?

**Comment by daniel-j-h** [comment]
Potentially this one: https://github.com/mapbox/robosat/pull/180

We compile for AVX2 to get some sweet speedups :racehorse: if you run on a machine without AVX2 instruction set support (introduced with Haswell, in 2013'ish), this could be the issue.

You can fix it by changing the CFLAGS in the Dockerfile(s) and then re-building the docker images.

Hope this helps.

**Comment by aleksandrmelnyk** [comment]
Daniel, thanks much, I'll give it a try.

**Comment by aleksandrmelnyk** [comment]
I have removed CFLAGS and rebuild docker image and it fixed issue.
thanks
