### ISSUE TITLE
Pretrained model?

### ISSUE THREAD

**Issue by aleksandrmelnyk** [mapbox/robosat#204]
Hi all,

Is there a pretrained model which could be applied for detecting objects on geospatial images? Just wondering if it is required to download and train mapbox data each time..?

thanks in advance.

**Comment by daniel-j-h** [comment]
I provide a pre-trained model for aerial data in Bavaria, see
- https://www.openstreetmap.org/user/daniel-j-h/diary/368771
- https://github.com/mapbox/robosat/releases/download/v1.2.0/bavaria-dop80-release-1.tar.gz

Other than that, there are no publicly available pre-trained models I'm aware of.

These models also highly depend on your use case, zoom level, region, etc.

**Comment by aleksandrmelnyk** [comment]
Daniel, thanks, good to know.
