### ISSUE TITLE
Error: CUDA requested but not available

### ISSUE THREAD

**Issue by madhu369** [mapbox/robosat#205]
Hi,
i executed the below command: 
>>>sudo docker run -it --rm -v $PWD:/data --ipc=host --network=host mapbox/robosat:latest-cpu predict --tile_size 256 --checkpoint release-01/bavaria-dop80-checkpoint.pth --model config/model-unet.toml --dataset config/dataset-parking.toml images output
output:
Error: CUDA requested but not available
i tried to change the model-unet.toml file but unable to recognize the changes
how can i change cuda = False in model-unet.toml file and commit changes in docker image
As i am new to docker so please let me know the solution for this issue.
Thank you.

**Comment by daniel-j-h** [comment]
You are missing

    --runtime=nvidia

in your docker run command line.

You will need [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) for it to work.
