### ISSUE TITLE
Update version of pyproj in requirements

### ISSUE THREAD

**Issue by Venka97** [mapbox/robosat#206]
To prevent the error mentioned in #176, the pyproj version needs to be updated. I use the version **2.4.0** and it works fine but rs merge fails with **2.1.3**, i.e. the version mentioned in [requirements.txt.](https://github.com/mapbox/robosat/blob/master/requirements.txt)

**Comment by daniel-j-h** [comment]
Yeap and also update pytorch and torchvision https://github.com/mapbox/robosat/issues/182

By now this project is unmaintained, see for context https://github.com/mapbox/robosat/issues/184
