### ISSUE TITLE
Available pre-trained models

### ISSUE THREAD

**Issue by charleygros** [mapbox/robosat#213]
Hi there,

I found this [trained model](https://www.openstreetmap.org/user/daniel-j-h/diary/368771), which is very useful. I was wondering if other models of this kind are publicly available, eg road, building segmentation from aerial RGB images.

Cheers

**Comment by daniel-j-h** [comment]
:wave: Hey hey, please check this issue and the note
- https://github.com/mapbox/robosat/issues/204
- https://github.com/mapbox/robosat/blob/cbb1c73328183afd2d6351b7bfa3f430b73103ea/README.md

Thank you and happy weekend! :v:

**Comment by charleygros** [comment]
Many thanks @daniel-j-h ! Appreciated
