### ISSUE TITLE
wrong docs: `rs download` requires the URL

### ISSUE THREAD

**Issue by rory** [mapbox/robosat#22]
The [Readme](https://github.com/mapbox/robosat/blob/121057b96607d2ae9b2740edfa15fd607c1cb9b0/README.md) says for `rs download`:

> Downloads aerial or satellite imagery from the Mapbox Maps API (by default) based on a list of tiles.

But the command requires the URL to be entered, and there is no default as far as I can see

**Comment by daniel-j-h** [comment]
Ah, good catch. We refactored the downloader tool to work with arbitrary tile sizes and endpoints but forgot to adapt the docs. Here is how you can download from the Mapbox Maps API:

    $ ./rs download 'https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}@2x.webp?access_token=TOKEN' /tmp/tiles.txt /tmp/images
