### ISSUE TITLE
Meaning of the QoD Metric

### ISSUE THREAD

**Issue by SBCV** [mapbox/robosat#221]
The `robosat.pink` repository uses by default a metric called `QoD`- see for example this [link](https://github.com/SBCV/robosat.pink/blob/master/robosat_pink/metrics/qod.py).

Does anyone know the meaning of the `QoD` metric or a paper that defines this metric? I'm not even sure, what the meaning of the acronym `QoD` is.

I'm aware that `robosat.pink` is only a fork of `robosat`. But since Olivier passed away, I do not know where else to ask this question. If you think this is not the right place for this question, feel free to close it.

**Comment by daniel-j-h** [comment]
I am sorry, I do not know.

**Comment by SBCV** [comment]
No problem - still thank you for answering. I guess if you have no idea, nobody does.
