### ISSUE TITLE
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mapbox/mapbox-maps-android?pullRequest=1777) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mapbox/mapbox-maps-android?pullRequest=1777) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mapbox/mapbox-maps-android?pullRequest=1777) it.</sub>

### ISSUE THREAD

**Issue by bomturbo** [mapbox/robosat#225]
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mapbox/mapbox-maps-android?pullRequest=1777) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mapbox/mapbox-maps-android?pullRequest=1777) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mapbox/mapbox-maps-android?pullRequest=1777) it.</sub>

_Originally posted by @CLAassistant in https://github.com/mapbox/mapbox-maps-android/issues/1777#issuecomment-1287774713_

**Comment by daniel-j-h** [comment]
?
