### ISSUE TITLE
`rs download` only downloads first handful of tiles

### ISSUE THREAD

**Issue by rory** [mapbox/robosat#24]
I am trying to download the tiles for part of Ireland, and `rs download` only downloads the first ~300 tiles and then stops. When I run it again, it doesn't download anything more. This is the command I used and the output (I just prints the empty progress barm and exits after ~2 sec):

> ./rs download --rate 1 --ext jpg "https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=[ACCESTOKEN]" ./data/bld-cover.csv ./data/tiles/
>   0%|                                                                                                                                                                                 | 0/28637 [00:00<?, ?image/s]

Maybe I have hit a limit in the Mapbox API, if so `rs download` should tell the user that.

**Comment by daniel-j-h** [comment]
> (I just prints the empty progress barm and exits after ~2 sec):

Sounds like it downloaded all images already. The tool first checks to see if images are already present and if so skips downloading again. On error we print warnings to stderr.

**Comment by tomass** [comment]
`rs cover` function creates a csv file with a list of tiles where tile numbers have duplicates.
This could be the reason why `rs download` shows "final count" much larger than actual number of tiles to be downloaded.
For example: I got a csv file with 700 rows. sort -u .csv > .csv.new creates a file with only 150 rows (which means there are only 150 unique rows).
When `rs download` is executed against original 700 row file, progress bar shows 700 as a "final count", but stops (as expected) at 150 downloaded tiles.

**Comment by daniel-j-h** [comment]
@tomass good catch! I changed that in https://github.com/mapbox/robosat/pull/34 to make sure the tile list generated by `rs cover` is unique.
