### ISSUE TITLE
Provide nvidia-docker Dockerfile for easy GPU environment setup

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/robosat#29]
We should provide a Dockerfile with the latest NVIDIA GPU drivers, the latest CUDA and cuDNN.

These docker containers can then be started via the `nvidia-docker` plugin to abstract away driver differences on the host which allows users to more easily getting started without manually having to go through the painful NVIDIA driver and package situation.

The goal here is to provide a self-contained Docker image for users ready to run the toolchain.

Tasks:
- [ ] Write Dockerfile for nvidia-docker plugin
- [ ] Install NVIDIA drivers, CUDA, cuDNN
- [ ] Install RoboSat deps. and make binaries `docker run`-able
- [ ] Test
- [ ] Write docs
- [ ] Set up [automated Docker Hub builds](https://docs.docker.com/docker-hub/builds/#link-to-a-hosted-repository-service)

**Comment by daniel-j-h** [comment]
Some notes here:
- https://pytorch.org for PyTorch wheel which depends on Python + CUDA versions
- https://hub.docker.com/r/nvidia/cuda/ for nvidia-docker base images with CUDA, cuDNN pre-installed
- https://gitlab.com/nvidia/cuda for nvidia-docker base image sources

**Comment by jjmata** [comment]
This looks like a nice starting point: https://github.com/anibali/docker-pytorch ;-)

**Comment by jjmata** [comment]
Since `nvidia-docker` 2.0 is out now this should probably be simpler ...

**Comment by jjmata** [comment]
Putting my money^H^H^H^H^Htime where my mouth is: https://github.com/splashblot/docker-pytorch/tree/robosat ... 😄

**Comment by daniel-j-h** [comment]
@jjmata interesting! If you open a pull request and put a `Dockerfile` into this repository we can automatically have Docker Hub build and publish Docker images for every commit.
