### ISSUE TITLE
Validation sample folder documentation

### ISSUE THREAD

**Issue by tomass** [mapbox/robosat#36]
`rs train` is missing documentation about validation samples. In particular that it needs folders similar to the ones in _training_ folder:
- %base%/validation/images/
- %base%/validation/labels/

Without these folders (and actual data in them) training crashes after 1st epoch with not so obvious message: 

```
Epoch: 1/10
Train: 100%|#################################| 10/10 [07:58<00:00, 47.82s/batch]
Train loss: 0.3844, mean IoU: 0.2952
Validate: 0batch [00:00, ?batch/s]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/robosat/tools/__main__.py", line 42, in <module>
    args.func(args)
  File "/home/robosat/tools/train.py", line 105, in main
    val_hist = validate(val_loader, num_classes, device, net, criterion)
  File "/home/robosat/tools/train.py", line 186, in validate
    return {'loss': running_loss / num_samples, 'iou': iou.get()}
ZeroDivisionError: division by zero
```

P.S. Clear error message would also help.

**Comment by daniel-j-h** [comment]
The errors you are seeing are from the train and validate steps per epoch where we currently assume that there are always samples available. If no samples are available we run into the div-by-zero issue.

We should add checks to make sure we get at least a single sample in both training and validation here
- https://github.com/mapbox/robosat/blob/6c8a6b69346a48ce0469d7f70f5959ab2a3a02f3/robosat/tools/train.py#L152
- https://github.com/mapbox/robosat/blob/6c8a6b69346a48ce0469d7f70f5959ab2a3a02f3/robosat/tools/train.py#L185

and then show a clear error message when we run into it. And document the directory structure.

Thanks for flagging!

**Comment by JannisEgelhof** [comment]
I still get the same error. 

`Loading: 100%|##########################| 3046/3046 [00:13<00:00, 229.93image/s]
[1.543922, 8.250376]
--- Hyper Parameters on Dataset: /data/ ---
Batch Size:      128
Image Size:      256
Learning Rate:   0.0001
Loss function:   Lovasz
Weights :        [1.6248, 5.762827]
---
Epoch: 1/10
Train: 100%|#################################| 23/23 [01:13<00:00,  2.37s/batch]
Train    loss: 0.0050, mIoU: 0.447, building IoU: 0.038, MCC: 0.010
Validate: 0batch [00:00, ?batch/s]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/robosat/tools/__main__.py", line 58, in <module>
    args.func(args)
  File "/usr/src/app/robosat/tools/train.py", line 143, in main
    val_hist = validate(val_loader, num_classes, device, net, criterion)
  File "/opt/conda/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/src/app/robosat/tools/train.py", line 234, in validate
    "loss": running_loss / num_samples,
ZeroDivisionError: division by zero
`

**Comment by daniel-j-h** [comment]
Hm you should get an assertion here

https://github.com/mapbox/robosat/blob/1d0cf506cde4600ab7063c238f7f9e25d65ba611/robosat/tools/train.py#L270-L271

when we create the dataloaders and detect that your train or validation dataset is empty.

Which gitsha or robosat version are you running? Can you reproduce this in a small self-contained example using the official docker images? It looks like you are using conda.
