### ISSUE TITLE
Unable to load model weights: `rs train` should always use DataParallel

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/robosat#41]
The DataParallel wrapper slightly changes the model's internal layer names. In `rs predict` as well as `rs serve` we always wrap the model in a DataParallel wrapper, both for CUDA as well as for prediction on CPUs.

In contrast `rs train` currently only uses the DataParallel wrapper when using CUDA. This can lead to the following problem: when training on CPUs, then saving the checkpoints without the DataParallel wrapper, and then predicting (with CUDA or CPUs) loading the model fails with cryptic error messages since the model's layer names now don't match up.

Task
- [ ] Always wrap model in DataParallel in `rs train`
- [ ] Test training on CPUs, and then predicting on both CUDA as well as CPUs
- [ ] Test training on GPUs, and then predicting on both CUDA as well as CPUs

**Comment by tomass** [comment]
Temporary note for other testers: currently, when training on cpu, `nn.DataParallel(net)` has to be commented out in `predict.py` for prediction to work:

```
net = UNet(num_classes).to(device)
#net = nn.DataParallel(net) # <--------- commented out

if cuda:
  torch.backends.cudnn.benchmark = True
```
