### ISSUE TITLE
Time to download will take a year

### ISSUE THREAD

**Issue by CraigglesO** [mapbox/robosat#53]
I am trying to do building extraction for the state of Utah as the best data is about 14,000 houses so far (Microsoft building footprint data). Almost all of the houses are on the north side of Salt Lake City, so really not a huge total footprint.

Currently it says it's going to take about 333 days to download the corresponding raster data from `./rs download ... `

I don't even think I can use a free subscription to download all this data. Is their something else I can do to get the raster data?

BTW - I didn't understand why the `cover` command needed a zoom, since building data is small, I just set it to 22:
`./rs cover ../building-extraction.geojson --zoom 22 ../cover-tiles.csv`

I am sure that's not a problem though...

Any ideas? Is there a program to send in a hard drive for the raster data?

Thanks,
Craig,

**Comment by daniel-j-h** [comment]
`rs download` comes with a `--rate` argument that you can set e.g. to 100.

`rs cover` needs a zoom level since it will rasterize building masks for a specific zoom level then. You have to pass the same zoom level to all tools. For example if you download z20 images you also want z20 masks.

For buildings I would try with z19 or z20 first, z22 sounds way too high.

**Comment by CraigglesO** [comment]
@daniel-j-h - Thanks for the speedy response! I should have shown you all my commands, I think I did everything right including the rate, however, changing the zoom to 19 was a good idea.

Although it is still claiming to take about 100 days, in reality it should only take about a day now that I am tracking how long it takes for 1% increments.

Excited to try this.
I've also been having interesting results with competition code for building detection:
https://github.com/SpaceNetChallenge/BuildingDetectors_Round2

Thanks,
Craig.
