### ISSUE TITLE
Remove support for resuming from a checkpoint

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/robosat#59]
At the moment we a resume feature in place for training where users can resume training from a checkpoint.

https://github.com/mapbox/robosat/blob/2067cb7429ffd95efc3d9ace255b234831615d39/robosat/tools/train.py#L43

Initially we were thinking about using this feature to speed up subsequent training runs and do fine-tuning.

We actually never used it, it's not properly tested, and we don't have a use-case for it anymore. We should remove the code which comes with this feature and simplify our training script.

Task
- [ ] remove resume feature from `rs train`

**Comment by CraigglesO** [comment]
I wish this was still in, as for me, after an epoch it keeps crashing, so having this would be GREAT. But I guess I can just dig it up and copy paste it into my version.

**Comment by daniel-j-h** [comment]
@CraigglesO we should probably get down to _why_ it's crashing. You said after one epoch? Could it be that you don't have a lot of GPU memory and the training epoch barely fits on the GPU? Then when we switch from training to validation we need some additional memory. If so you can lower the batch size. Please open a separate ticket for your issue. I still don't feel this issue justifies bringing back this changeset.
