### ISSUE TITLE
Automatically generate a road training set based on OpenStreetMap

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/robosat#6]
We need a training set with road masks for the areas we have high-resolution satellite imagery for.

Repeat process in https://github.com/mapbox/robosat/issues/15 with roads. The tag we care about is `highway=*`. In OpenStreetMap:
- https://wiki.openstreetmap.org/wiki/Highways
- https://wiki.openstreetmap.org/wiki/Key:highway

For road width in addition to width and lane tags:
* [`parking:lane=*`](https://wiki.openstreetmap.org/wiki/Key:parking:lane)
* [`cycleway=lane`](https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dlane)
* [`busway=lane`](https://wiki.openstreetmap.org/wiki/Tag:busway%3Dlane)
* [`expressway=*`](https://wiki.openstreetmap.org/wiki/Key:expressway)

Problems and open questions:
- Roads in OpenStreetMap are modelled with ways and not polygons. Which means we can only guestimate their width (look into road width and lane tags) to create a mask for them. We can also use the highway classification (think: primary vs service roads).
- The road classification does not have to be consistent. A primary road in SF could be tagged secondary in DC. Does it make sense to create our own road classes, e.g. paved / unpaved?
- Do we want a binary road / not road binary classifier or do we e.g. want to be able to detect link roads? Can we distinguish link roads from the imagery?

Tasks:
- [ ] Check which highway tags we want
- [ ] Check if highway classification is the same across geographies
- [ ] Check which tags to use for road width estimation
- [ ] Implement osmium handler for `rs extract`
- [ ] Spec out ticket for road post-processing

**Comment by jjmata** [comment]
Need help here, @daniel-j-h?  Would love to discuss ...

**Comment by daniel-j-h** [comment]
Yes sure, if you want to help here that would be amazing! Here are some notes for how to approach this:
- You need to add a new handler for `rs extract` (e.g. `robosat/osm/roads.py`) which turns OpenStreetMap way geometries into polygon shapes. Take a look at the [existing handlers](https://github.com/mapbox/robosat/tree/421ea6a824b513c7856875f46a6641d98c637787/robosat/osm).
- You need to import and add the road handler then in `robosat/tools/extract.py`
- In the road handler you need to filter out every way that does not have the [highway=*](https://wiki.openstreetmap.org/wiki/Key:highway) tag
- In the road handler you need to estimate the road width based on tags like: width, lane tags, parking=lane, cycleway=lane, busway=lane, expressway=*. And if no such tags are available come up with a reasonable default. Note: from experience, it doesn't have to be super precise the model will learn from lots of images and work with his kind of noise.
- You can then buffer the way with your width estimate to turn the way linestring into a polygon shape.
- You need to think of edge-cases like steps. Do we want to include them? Maybe not. Both paved and unpaved roads? Maybe. Should it depend on the zoom level? Maybe.

You can put the way object into a shapely shape. Then use the buffer function to turn it into a polygon. And then use the mapping function to go back from shapely shape to geojson.
- http://toblerity.org/shapely/shapely.geometry.html#shapely.geometry.base.BaseGeometry.buffer
- http://toblerity.org/shapely/shapely.geometry.html#shapely.geometry.geo.mapping

Hope that helps; let me know if things are unclear.

**Comment by DragonEmperorG** [comment]
About the road width estimation, how's it going? Could we just simply give fixed value according to some standard.

**Comment by daniel-j-h** [comment]
@DragonEmperorG implemented this in https://github.com/mapbox/robosat/pull/111.

We should open up a new ticket about roads post-processing and how to best implement it.
