### ISSUE TITLE
Include matplotlib.use('Agg') in the utils.py

### ISSUE THREAD

**Issue by maning** [mapbox/robosat#62]
This line imports on the pyplot https://github.com/mapbox/robosat/blob/b2b6df26dd091da9344982d440c536b90ec30e4f/robosat/utils.py#L1

Any reason not to include the following lines below?

```
import matplotlib
matplotlib.use('Agg')

```

The README [mentions this as environment variable](https://github.com/mapbox/robosat/blob/master/README.md#rs-train), putting it directly in the code avoid setting this up in your environment.

**Comment by daniel-j-h** [comment]
No specific reason we are not setting the Agg backend in the code directly other than letting the user specify it via environment variables. I'm fine with setting it in code directly if that makes things easier. Want to open a pull request?
