### ISSUE TITLE
Clarify that the model toml file is a template

### ISSUE THREAD

**Issue by maning** [mapbox/robosat#63]
For a beginner, using the provided config parameters can give unexpected results.  This happened to me unaware that some of these settings should be edited.  Below are some of my changes.

```

--- a/config/model-unet.toml
+++ b/config/model-unet.toml
@@ -15,10 +15,10 @@
   batch_size = 2
 
   # Image side size in pixels.
-  image_size = 512
+  image_size = 256
 
   # Directory where to save checkpoints to during training.
-  checkpoint = '/tmp/pth/'
+  checkpoint = '/data/robosat/tmp/pth/'
```

Propose we make it explicit that these are templates that should edited before running a training.

**Comment by tomass** [comment]
@jjmata I've successfully went through the process (up to predict) with 256x256 tiles. You have to change _model-unet.toml_ file and give "256" parameters to some other tools.

**Comment by daniel-j-h** [comment]
@maning Agree we should document the configurations better. Do you want to open a pull request adding some clarifying words to the readme?

@jjmata @tomass we were running the pipeline with 512x512 images at first for efficiency reasons but by now the pipeline works with 256x256, too. Or 1024x1024, or even higher (as long as you can fit the images into GPU memory for training). Same here: we probably should document that better.
