### ISSUE TITLE
Virtualenv support - installation

### ISSUE THREAD

**Issue by mcavdar** [mapbox/robosat#82]
Virtualenv can be added into [installation](https://github.com/mapbox/robosat#installation) instructions.

**Comment by daniel-j-h** [comment]
Do you want to open a pull request for that?

The reason we didn't add virtualenv to the install instructions is that it's orthogonal to installing the dependencies. In addition there are some slight differences with how to set up the virtualenv environment. Some folks will have the `virtualenv` binary at hand others need to use `python3 -m venv`, etc.

**Comment by daniel-j-h** [comment]
Resolved in https://github.com/mapbox/robosat/pull/84.
