### ISSUE TITLE
Installation problem with the boost_python lib.

### ISSUE THREAD

**Issue by DragonEmperorG** [mapbox/robosat#85]
After I finished the Installation instruction on Ubuntu 16.04, I tried to test the tool working state:
`./rs --help`
 the tool returned the Import Error:
`Traceback (most recent call last):`
  `File "/home/ql/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)`
  `File "/home/ql/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)`
  `File "/home/ql/GitHubRepo/robosat/robosat/tools/__main__.py", line 5, in <module>
    from robosat.tools import (`
  `File "/home/ql/GitHubRepo/robosat/robosat/tools/extract.py", line 3, in <module>
    from robosat.osm.parking import ParkingHandler`
  `File "/home/ql/GitHubRepo/robosat/robosat/osm/parking.py", line 3, in <module>
    import osmium`
  `File "/home/ql/anaconda3/envs/pytorch/lib/python3.6/site-packages/osmium/__init__.py", line 1, in <module>
    from osmium._osmium import *`
`ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0: undefined symbol: PyClass_Type`
I thought there might be something wrong with the Boost_Python lib, how could I figure it out?

**Comment by daniel-j-h** [comment]
You are running into https://github.com/osmcode/pyosmium/issues/52. The ticket has a workaround at the bottom. You have Python3.6 installed (probably through a ppa) but the Ubuntu 16.04 system comes with Boost.Python for Python3.5.

**Comment by DragonEmperorG** [comment]
Thanks for your quick reply. I used conda to create a new Environment with python=3.5. After I replayed all the installation operations, Robosat works fine. Sorry for the noise. Feel free to close.

**Comment by daniel-j-h** [comment]
:+1: hopefully at some point we will just have self-contained Docker images.

Have fun with :robot: :framed_picture:!
