### ISSUE TITLE
Error "always single hierarchy for all polygons in multipolygon"

### ISSUE THREAD

**Issue by toren77** [mapbox/robosat#90]
I try to extract features from Berlin parking dataset  I created to follow robosat utility instructions.

rs features --type parking --dataset config/dataset-parking.toml segmentation-masks/berlin-parking  GeoJSON_features/berlin-parking

Traceback (most recent call last):
  File "/anaconda3/envs/robosat/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/robosat/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/robosat/robosat/tools/__main__.py", line 57, in <module>
    args.func(args)
  File "/robosat/robosat/tools/features.py", line 49, in main
    handler.apply(tile, mask)
  File "/robosat/robosat/features/parking.py", line 48, in apply
    assert len(hierarchy) == 1, "always single hierarchy for all polygons in multipolygon"
TypeError: object of type 'NoneType' has no len() 

1) Could the problem be solved internally in robosat ? 
2) What tool may help to bring multipolygons to single hierarchy meanwhile ? 

Thanks !

**Comment by daniel-j-h** [comment]
That's an error on our side: hierarchy can be `None`. We need a check for that.

@bkowshik it seems like you fixed this in https://github.com/mapbox/robosat/pull/64/files could you run it out. There are some comments in the pr still open) so that we can merge it? Or at least split off the hierarchy check.

@toren77 you can add the `None` check locally for now; should fix your problems.

**Comment by toren77** [comment]
Thanks for rapid answer , 

  File "/robosat/robosat/features/parking.py", line 49, in apply
    hierarchy = hierarchy[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by daniel-j-h** [comment]
Like I said you will need the fix from https://github.com/mapbox/robosat/pull/64/files. You can add

```python
if hierarchy is None:
    return
```

here

https://github.com/mapbox/robosat/blob/6c7f547d2dd303f8a68b4fbd2ba60583348d7816/robosat/features/parking.py#L45

**Comment by toren77** [comment]
the fix works for me
Here is output 

35%|################################4                                                           | 3889/11025 [01:23<02:32, 46.70mask/s]Warning: extracted feature is not valid, skipping
 66%|############################################################9                               | 7304/11025 [02:35<01:19, 46.99mask/s]Warning: extracted feature is not valid, skipping
 67%|#############################################################3                              | 7347/11025 [02:36<01:18, 46.99mask/s]Warning: extracted feature is not valid, skipping
 72%|#################################################################8                          | 7892/11025 [02:48<01:06, 46.81mask/s]Warning: extracted feature is not valid, skipping
100%|###########################################################################################| 11025/11025 [03:54<00:00, 47.05mask/s]
